<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEJJVtr3\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEJJVtr3/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEJJVtr3.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEJJVtr3\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerEJJVtr3\appAppKernelProdContainer([
    'container.build_hash' => 'EJJVtr3',
    'container.build_id' => 'f6902bb0',
    'container.build_time' => 1696967605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEJJVtr3');
