CREATE TABLE USUARIO(
    NICK VARCHAR(20),
    NOMBRE VARCHAR(45) not null,
    APELLIDO VARCHAR(45),
    EMAIL VARCHAR(45) not null,
    PASSWORD VARCHAR(45) not null,
    PRIMARY KEY(NICK)
);

CREATE TABLE CANCION(
    ID INT AUTO_INCREMENT,
    BITRATE INT,
    GENERO VARCHAR(20),
    AUTOR VARCHAR(50),
    TITULO VARCHAR(50),
    FECHA DATE,
    DURACION TIME,
    USUARIO_NICK VARCHAR(20),
    PRIMARY KEY(ID)
);

CREATE TABLE LISTA_REPRODUCCION(
    ID INT AUTO_INCREMENT,
    NOMBRE_LISTA VARCHAR(50),
    USUARIO_NICK VARCHAR(20),
    PRIMARY KEY(ID)
);


CREATE TABLE CANCION_LISTA(
    ORDEN INT,
    CANCION_ID INT,
    LISTA_REPRODUCCION_ID INT,
    PRIMARY KEY(CANCION_ID,LISTA_REPRODUCCION_ID)
);

-- CLAVES FORANEAS

ALTER TABLE CANCION
ADD CONSTRAINT FK_CANCION_USUARIO
FOREIGN KEY (USUARIO_NICK) REFERENCES USUARIO(NICK);

ALTER TABLE CANCION_LISTA
ADD CONSTRAINT FK_CANCION_CANCION
FOREIGN KEY(CANCION_ID) REFERENCES CANCION(ID);

ALTER TABLE CANCION_LISTA
ADD CONSTRAINT FK_CANCION_LISTA
FOREIGN KEY(LISTA_REPRODUCCION_ID) REFERENCES LISTA_REPRODUCCION(ID);

ALTER TABLE LISTA_REPRODUCCION
ADD CONSTRAINT FK_LISTA_USUARIO
FOREIGN KEY (USUARIO_NICK) REFERENCES USUARIO(NICK);

-- INSERCIONES
INSERT INTO USUARIO
VALUES("moios","MOISES","A","moios@a.com","12345");

INSERT INTO USUARIO(nick,nombre,email,password)
VALUES("kami","Camila","cami@gmail.com","12345");

INSERT INTO CANCION
VALUES(default,320, "KPOP","BTS",
"FAKE LOVE","2021-01-02","0:2:50","moiosSAFS");

INSERT INTO CANCION
VALUES(default,320, "KPOP","BTS",
"GO GO","2021-02-02","0:2:40","moios");

INSERT INTO CANCION
VALUES(default,320, "KPOP","BLACKPINK",
"MONEY","2021-04-15","0:2:10","moios");
