<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBsSiQxN\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBsSiQxN/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBsSiQxN.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBsSiQxN\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBsSiQxN\appAppKernelProdContainer([
    'container.build_hash' => 'BsSiQxN',
    'container.build_id' => 'd1764c4b',
    'container.build_time' => 1696967562,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBsSiQxN');
